/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget {
  'id' : bigint,
  'month' : string,
  'userId' : Principal,
  'monthlyLimit' : number,
  'currency' : string,
  'category' : string,
}
export interface Investment {
  'id' : bigint,
  'userId' : Principal,
  'date' : bigint,
  'name' : string,
  'currentValue' : number,
  'currency' : string,
  'initialAmount' : number,
  'notes' : string,
  'investmentType' : string,
}
export interface SavingsGoal {
  'id' : bigint,
  'userId' : Principal,
  'name' : string,
  'description' : string,
  'targetAmount' : number,
  'currency' : string,
  'targetDate' : bigint,
  'currentAmount' : number,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : string,
  'isRecurring' : boolean,
  'userId' : Principal,
  'date' : bigint,
  'description' : string,
  'recurringPeriod' : [] | [string],
  'currency' : string,
  'category' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInvestment' : ActorMethod<[Investment], bigint>,
  'addSavingsGoal' : ActorMethod<[SavingsGoal], bigint>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBudget' : ActorMethod<[bigint], undefined>,
  'deleteInvestment' : ActorMethod<[bigint], undefined>,
  'deleteSavingsGoal' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getBudgetsByMonth' : ActorMethod<[string], Array<Budget>>,
  'getBudgetsForCaller' : ActorMethod<[], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestmentById' : ActorMethod<[bigint], [] | [Investment]>,
  'getInvestmentsForCaller' : ActorMethod<[], Array<Investment>>,
  'getSavingsGoalById' : ActorMethod<[bigint], [] | [SavingsGoal]>,
  'getSavingsGoalsForCaller' : ActorMethod<[], Array<SavingsGoal>>,
  'getTransactionById' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<Transaction>
  >,
  'getTransactionsForCaller' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudget' : ActorMethod<[Budget], bigint>,
  'updateInvestment' : ActorMethod<[Investment], undefined>,
  'updateSavingsGoal' : ActorMethod<[SavingsGoal], undefined>,
  'updateTransaction' : ActorMethod<[Transaction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];