/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Investment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'currentValue' : IDL.Float64,
  'currency' : IDL.Text,
  'initialAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'investmentType' : IDL.Text,
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'currency' : IDL.Text,
  'targetDate' : IDL.Int,
  'currentAmount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Text,
  'isRecurring' : IDL.Bool,
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'recurringPeriod' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'userId' : IDL.Principal,
  'monthlyLimit' : IDL.Float64,
  'currency' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInvestment' : IDL.Func([Investment], [IDL.Nat], []),
  'addSavingsGoal' : IDL.Func([SavingsGoal], [IDL.Nat], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBudget' : IDL.Func([IDL.Nat], [], []),
  'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
  'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getBudgetsByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Budget)], ['query']),
  'getBudgetsForCaller' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Investment)], ['query']),
  'getInvestmentsForCaller' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'getSavingsGoalById' : IDL.Func([IDL.Nat], [IDL.Opt(SavingsGoal)], ['query']),
  'getSavingsGoalsForCaller' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getTransactionById' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactionsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsForCaller' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudget' : IDL.Func([Budget], [IDL.Nat], []),
  'updateInvestment' : IDL.Func([Investment], [], []),
  'updateSavingsGoal' : IDL.Func([SavingsGoal], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Investment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'currentValue' : IDL.Float64,
    'currency' : IDL.Text,
    'initialAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'investmentType' : IDL.Text,
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'currency' : IDL.Text,
    'targetDate' : IDL.Int,
    'currentAmount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Text,
    'isRecurring' : IDL.Bool,
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'recurringPeriod' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'userId' : IDL.Principal,
    'monthlyLimit' : IDL.Float64,
    'currency' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInvestment' : IDL.Func([Investment], [IDL.Nat], []),
    'addSavingsGoal' : IDL.Func([SavingsGoal], [IDL.Nat], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBudget' : IDL.Func([IDL.Nat], [], []),
    'deleteInvestment' : IDL.Func([IDL.Nat], [], []),
    'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getBudgetsByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Budget)], ['query']),
    'getBudgetsForCaller' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestmentById' : IDL.Func([IDL.Nat], [IDL.Opt(Investment)], ['query']),
    'getInvestmentsForCaller' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'getSavingsGoalById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SavingsGoal)],
        ['query'],
      ),
    'getSavingsGoalsForCaller' : IDL.Func(
        [],
        [IDL.Vec(SavingsGoal)],
        ['query'],
      ),
    'getTransactionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getTransactionsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsForCaller' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudget' : IDL.Func([Budget], [IDL.Nat], []),
    'updateInvestment' : IDL.Func([Investment], [], []),
    'updateSavingsGoal' : IDL.Func([SavingsGoal], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };